// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WOLMeshWebAPI.DB;

namespace WOLMeshWebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("WOLMeshWebAPI.DB.DeviceNetworkDetails", b =>
                {
                    b.Property<long>("internalkey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceID")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkID")
                        .HasColumnType("INTEGER");

                    b.HasKey("internalkey");

                    b.ToTable("MachineNetworkDetails");
                });

            modelBuilder.Entity("WOLMeshWebAPI.DB.MachineItems", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcastAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeardFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastWakeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("WOLMeshWebAPI.DB.ManualMachineItems", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastHeardFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastWakeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("broadCastAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isOnline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastKnownIP")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("ManualMachines");
                });

            modelBuilder.Entity("WOLMeshWebAPI.DB.Networks", b =>
                {
                    b.Property<int>("NetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BroadcastAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubnetMask")
                        .HasColumnType("TEXT");

                    b.HasKey("NetworkID");

                    b.ToTable("Networks");
                });
#pragma warning restore 612, 618
        }
    }
}
